version: 3.0.3.{build}

environment:
  NUGET_PACKAGE_VERSION: "3.0.3-CI-{build}"

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "3.0.0.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build: nuget restore

build:
  verbosity: minimal
  publish_nuget: false
  publish_nuget_symbols: false

on_success:
  - cmd: nuget pack src\Autofac.Integration.Mef\Autofac.Integration.Mef.nuspec -Symbols -Properties "Configuration=%CONFIGURATION%;Platform=AnyCPU" -Version %NUGET_PACKAGE_VERSION%

artifacts:
  - path: '**\*.nupkg'

deploy:
- provider: NuGet
  server: https://www.myget.org/F/autofac/
  api_key:
    secure: N4KZCRegcmenMoJ0peZfQwDzqq+Wt4oxGzNTgvkrDxgWyZhw7hNwKmd4n2AsNKQX
  symbol_server: https://nuget.symbolsource.org/MyGet/autofac