version: 3.0.3.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "3.0.0.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "3.0.3"

configuration: Release