version: 3.0.3.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "3.0.0.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "3.0.3"

configuration: Release

before_build: nuget restore

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

deploy:
- provider: NuGet
  server: https://www.myget.org/F/autofac/
  api_key:
    secure: po0Rep+BsbvwbbM9mjLwYQ7rw6lVvc5sB6L+LgeKRY8W+89k386kkeSO/tttgzGi
  symbol_server: https://nuget.symbolsource.org/MyGet/autofac